name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pytest:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - os: macos-latest
            python-version: "3.8"

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - run: brew install libomp
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.cfg.python-version }}
      - run: pip install poetry
      - run: poetry install
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --verbose --all-files
      - run: poetry run pytest
